### ISSUE TITLE
enable report plugins

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#41]
somehow there's no reporting plugins to be seen anywhere.
the code is there, but it does not get through.

**Comment by mfrasca** [comment]
2015-05-29 11:52:00,044 - bauble.plugins.report - DEBUG - Traceback (most recent call last):
      File "/home/mario/.virtualenvs/bacl/local/lib/python2.7/site-packages/bauble-1.0.26-py2.7.egg/bauble/plugins/report/__init__.py", line 611, in start
        dialog = ReportToolDialog()
      File "/home/mario/.virtualenvs/bacl/local/lib/python2.7/site-packages/bauble-1.0.26-py2.7.egg/bauble/plugins/report/__init__.py", line 581, in __init__
        self.presenter = ReportToolDialogPresenter(self.view)
      File "/home/mario/.virtualenvs/bacl/local/lib/python2.7/site-packages/bauble-1.0.26-py2.7.egg/bauble/plugins/report/__init__.py", line 310, in __init__
        self.init_formatter_combo()
      File "/home/mario/.virtualenvs/bacl/local/lib/python2.7/site-packages/bauble-1.0.26-py2.7.egg/bauble/plugins/report/__init__.py", line 501, in init_formatter_combo
        if issubclass(p, FormatterPlugin):
    TypeError: issubclass() arg 1 must be a class
