### ISSUE TITLE
'SourceDetail' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by mfrasca** [Bauble/bauble.classic#65]
Traceback (most recent call last):
      File "/home/mario/.virtualenvs/bacl/local/lib/python2.7/site-packages/bauble-1.0.31-py2.7.egg/bauble/plugins/garden/accession.py", line 1460, in on_new_source_button_clicked
        e = SourceDetailEditor(parent=self.view.get_window())
      File "/home/mario/.virtualenvs/bacl/local/lib/python2.7/site-packages/bauble-1.0.31-py2.7.egg/bauble/plugins/garden/source.py", line 326, in __init__
        self.presenter = SourceDetailEditorPresenter(self.model, view)
      File "/home/mario/.virtualenvs/bacl/local/lib/python2.7/site-packages/bauble-1.0.31-py2.7.egg/bauble/plugins/garden/source.py", line 273, in __init__
        self.refresh_view()
      File "/home/mario/.virtualenvs/bacl/local/lib/python2.7/site-packages/bauble-1.0.31-py2.7.egg/bauble/plugins/garden/source.py", line 297, in refresh_view
        self.model[field]))
    TypeError: 'SourceDetail' object has no attribute '__getitem__'

**Comment by mfrasca** [comment]
bbb3943
